# Generated by Django 2.2.2 on 2019-07-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='horario.Curso'),
        ),
    ]
