# Generated by Django 2.2.2 on 2019-07-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_auto_20190713_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Curso'),
        ),
    ]
